name: school_vahan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.8.0
  geocoding: ^2.0.5
  firebase_core: ^1.22.0
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.2.0
  dropdown_search: ^5.0.2
  cloud_firestore: ^3.4.7
  flutter_secure_storage: ^6.0.0
  firebase_database: ^9.1.4
  geolocator: ^9.0.1
  map_picker: ^0.0.3
  flutter_svg: ^1.1.5
  firebase_app_check: ^0.0.7+1
  pinput: ^2.2.31
  url_launcher: ^6.0.20
  http: ^0.13.4
  permission_handler: ^10.0.1
  flutter_polyline_points: ^1.0.0
  firebase_messaging:
  flutter_local_notifications: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  image_path: "images/logo.jpg"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/busIcon.png
    - images/location_icon.svg
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
